
DROP TABLE IF EXISTS CATEGORIES;

CREATE TABLE CATEGORIES (
  id integer(20) NOT NULL,
  name varchar(255) DEFAULT NULL,
  PRIMARY KEY (id)
);

INSERT INTO CATEGORIES VALUES (1,'French');
INSERT INTO CATEGORIES VALUES (2,'Frozen Yogurt');
INSERT INTO CATEGORIES VALUES (3,'Gastropubs');
INSERT INTO CATEGORIES VALUES (4,'Coffee Houses');
INSERT INTO CATEGORIES VALUES (5,'Barbecue');
INSERT INTO CATEGORIES VALUES (6,'American');
INSERT INTO CATEGORIES VALUES (7,'Pizza');
INSERT INTO CATEGORIES VALUES (8,'Thai');
INSERT INTO CATEGORIES VALUES (9,'Sushi');
INSERT INTO CATEGORIES VALUES (10,'Indian');
INSERT INTO CATEGORIES VALUES (11,'Italian');
INSERT INTO CATEGORIES VALUES (12,'Burgers');
INSERT INTO CATEGORIES VALUES (13,'Vietnamese');
